//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class row_details
    {
        public int row_id { get; set; }
        public string row_no { get; set; }
        public string seats_filled { get; set; }
        public bool is_row_occupied { get; set; }

        public static explicit operator row_details(List<row_details> v)
        {
            throw new NotImplementedException();
        }
    }
}
