//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int applicant_id { get; set; }
        public string applicant_name { get; set; }
        public string row_no { get; set; }
        public Nullable<int> seat_no { get; set; }
    }
}
